site_name: naacl2025_token_weighting
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: naacl2025_token_weighting
      handlers:
        python:
          options:
            docstring_style: numpy